FROM golang:1.12-alpine AS builder

RUN apk --no-cache add ca-certificates git
RUN go get -v -u github.com/stripe/stripe-mock
RUN which stripe-mock

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /
COPY --from=builder /go/bin/stripe-mock .
ENTRYPOINT ["/stripe-mock", "-http-port", "12111", "-https-port", "12112"]
EXPOSE 12111
EXPOSE 12112
