ARG CI_BASE_IMAGE

FROM $CI_BASE_IMAGE

RUN apt-get install -y -qq --no-install-recommends git

RUN env ARTIFACTORY_USERNAME=$(echo ${ARTIFACTORY_USERNAME} | sed "s|@|%40|g") \
  pipenv install --ignore-pipfile --dev --deploy --system

RUN apt-get clean && \
    rm -rf /root/.cache
