ARG CI_BASE_IMAGE

FROM $CI_BASE_IMAGE

RUN apt-get install -y -qq --no-install-recommends \
    git && \
    pipenv install --ignore-pipfile --dev --system && \
    apt-get clean && \
    rm -rf /root/.cache
