@Library('common-pipelines@10.12.0') _

// -----------------------------------------------------------------------------------
// The following params are automatically provided by the callback gateway as inputs
// to the Jenkins pipeline that starts this job.
//
// CI pipeline for payment-service
//
// params["SHA"]                    - Sha used to start the pipeline
// params["BRANCH_NAME"]            - Name of GitHub branch the SHA is associated with
// params["UNIQUE_BUILD_ID"]        - A randomly generated unique ID for this job run
// params["ENQUEUED_AT_TIMESTAMP"]  - Unix timestamp generated by callback gateway
// params["JSON"]                   - Extensible json doc with extra information
// params["GITHUB_REPOSITORY"]      - GitHub ssh url of repository (git://....)
// -----------------------------------------------------------------------------------

pipeline {
  options {
    timestamps()
    skipStagesAfterUnstable()
    timeout(time: 30, unit: 'MINUTES')
  }
  agent {
    label 'universal'
  }
  stages {
    stage('Startup') {
      steps {
        setGitHubStatus 'Start Jenkinsfile-nodeploy Pipeline', 'Started'
        script {
          common = load "${WORKSPACE}/Jenkinsfile-common.groovy"
        }
      }
    }
    stage('Docker Build Tag Push') {
      steps {
        artifactoryLogin()
        script {
          common.buildTagPush(params['GITHUB_REPOSITORY'], params['SHA'], params['BRANCH_NAME'], common.getServiceName())
        }
      }
    }
    stage('Run CI container') {
      steps {
        script {
          common.runCIcontainer(common.getServiceName(), params['SHA'])
        }
      }
    }
    stage('Unit Tests') {
      steps {
        script {
          common.runUnitTests(common.getServiceName())
        }
      }
    }
    stage('Integration Tests') {
      steps {
        script {
          common.runIntegrationTests(common.getServiceName())
        }
      }
    }
    stage('Pulse tests') {
      steps {
        script {
          common.runPulseTests(common.getServiceName())
        }
      }
    }
    stage('Linting') {
      steps {
        script {
          common.runLinter(common.getServiceName())
        }
      }
    }
    stage('Typing') {
      steps {
        script {
          common.runTyping(common.getServiceName())
        }
      }
    }
    stage('Hooks') {
      steps {
        script {
          common.runHooks(common.getServiceName())
        }
      }
    }
  }
  post {
    always {
      script {
        common.removeAllContainers()
      }
    }
  }
}
