import pytest


@pytest.fixture
def sample_payment_method_webhook():
    return {
        "created": 1326853478,
        "livemode": False,
        "id": "evt_00000000000000",
        "type": "payment_method.attached",
        "object": "event",
        "request": None,
        "pending_webhooks": 1,
        "api_version": "2019-05-16",
        "account": "acct_00000000000000",
        "user_id": "acct_00000000000000",
        "data": {
            "object": {
                "id": "pm_00000000000000",
                "object": "payment_method",
                "billing_details": {
                    "address": {
                        "city": None,
                        "country": None,
                        "line1": None,
                        "line2": None,
                        "postal_code": None,
                        "state": None,
                    },
                    "email": "jenny@example.com",
                    "name": None,
                    "phone": "+15555555555",
                },
                "card": {
                    "brand": "visa",
                    "checks": {
                        "address_line1_check": None,
                        "address_postal_code_check": None,
                        "cvc_check": None,
                    },
                    "country": "US",
                    "description": "Visa Classic",
                    "exp_month": 8,
                    "exp_year": 2020,
                    "fingerprint": "rca24boD2K4iFl6k",
                    "funding": "credit",
                    "generated_from": None,
                    "iin": "424242",
                    "issuer": "Stripe Payments UK Limited",
                    "last4": "4242",
                    "three_d_secure_usage": {"supported": True},
                    "wallet": None,
                },
                "created": 123456789,
                "customer": None,
                "livemode": False,
                "metadata": {"order_id": "123456789"},
                "type": "card",
            }
        },
    }


@pytest.fixture
def sample_customer_subscription():
    return {
        "created": 1326853478,
        "livemode": False,
        "id": "evt_00000000000000",
        "type": "customer.subscription.deleted",
        "object": "event",
        "request": None,
        "pending_webhooks": 1,
        "api_version": "2019-08-14",
        "account": "acct_00000000000000",
        "user_id": "acct_00000000000000",
        "data": {
            "object": {
                "id": "sub_00000000000000",
                "object": "subscription",
                "application_fee_percent": None,
                "billing": "charge_automatically",
                "billing_cycle_anchor": 1566418839,
                "billing_thresholds": None,
                "cancel_at": None,
                "cancel_at_period_end": False,
                "canceled_at": None,
                "collection_method": "charge_automatically",
                "created": 1566418839,
                "current_period_end": 1569097239,
                "current_period_start": 1566418839,
                "customer": "cus_00000000000000",
                "days_until_due": None,
                "default_payment_method": None,
                "default_source": None,
                "default_tax_rates": [],
                "discount": None,
                "ended_at": 1566417156,
                "items": {
                    "object": "list",
                    "data": [
                        {
                            "id": "si_00000000000000",
                            "object": "subscription_item",
                            "billing_thresholds": None,
                            "created": 1566418840,
                            "metadata": {},
                            "plan": {
                                "id": "gold_00000000000000",
                                "object": "plan",
                                "active": True,
                                "aggregate_usage": None,
                                "amount": 2000,
                                "billing_scheme": "per_unit",
                                "created": 1394782612,
                                "currency": "cad",
                                "interval": "month",
                                "interval_count": 1,
                                "livemode": False,
                                "metadata": {},
                                "nickname": None,
                                "product": "prod_00000000000000",
                                "tiers": None,
                                "tiers_mode": None,
                                "transform_usage": None,
                                "trial_period_days": None,
                                "usage_type": "licensed",
                            },
                            "quantity": 1,
                            "subscription": "sub_00000000000000",
                            "tax_rates": [],
                        }
                    ],
                    "has_more": False,
                    "total_count": 1,
                    "url": "/v1/subscription_items?subscription=sub_FfKy8lGlrhTqkE",
                },
                "latest_invoice": None,
                "livemode": False,
                "metadata": {},
                "pending_setup_intent": None,
                "plan": {
                    "id": "gold_00000000000000",
                    "object": "plan",
                    "active": True,
                    "aggregate_usage": None,
                    "amount": 2000,
                    "billing_scheme": "per_unit",
                    "created": 1394782612,
                    "currency": "cad",
                    "interval": "month",
                    "interval_count": 1,
                    "livemode": False,
                    "metadata": {},
                    "nickname": None,
                    "product": "prod_00000000000000",
                    "tiers": None,
                    "tiers_mode": None,
                    "transform_usage": None,
                    "trial_period_days": None,
                    "usage_type": "licensed",
                },
                "quantity": 1,
                "schedule": None,
                "start": 1566418839,
                "start_date": 1566418839,
                "status": "canceled",
                "tax_percent": None,
                "trial_end": None,
                "trial_start": None,
            }
        },
    }
