VISA_DEBIT_CARD_TOKEN = "tok_visa_debit"
MASTER_CARD_DEBIT_CARD_TOKEN = "tok_mastercard_debit"
BANK_ACCOUNT_TOKEN = "btok_us_verified"
DEBIT_CARD_NUMBER = "4000056655665556"
TEST_DEFAULT_PAGE_SIZE = 10
